### PR TITLE
Update ja.json :ANALYTICS

### PR DESCRIPTION
**Pull request by maboroshin**
I done.

image
I want test that shortcut key of Japanese style in system tray. 

Does the following code (my pull request) look like this image?
```
    "GENERIC_QUIT": "終了(&X)",
```

### CODE REVIEW

**Comment by xanderfrangos** [comment]
Thanks for the update!

Yeah, this is what the pull request looks like on my machine:
shortcut

**Comment by maboroshin** [comment]
Oh! Thankyou!
Ok, no problem. It is correct!

**Comment by maboroshin** [comment]
There is no response to the alphabet of shortcut keys. So erase it via Weblate.

**Comment by maboroshin** [comment]
@xanderfrangos : Twinkle Tray has been [featured on the biggest website in Japan!](https://forest.watch.impress.co.jp/docs/review/1249550.html)😆

**Comment by xanderfrangos** [comment]
@maboroshin That would explain why most users are now from Japan. 😂

Annotation 2020-05-01 093702

I doubt it would have been featured without your translation. 👍

**Pull request merged**
