### PR TITLE
Added German localization.

### PR DESCRIPTION
**Pull request by CodeF0x**
Hi! I've added German localization and while I tested the changes locally, everything seemed to work fine and without any issues.

Some parts of the translation still use English words, as German does not really have equivalents for them. Either you know those words, or you don't.

I think the translation is not perfect, so I'm happy for suggestions and fixes from the community!

### CODE REVIEW

**Comment by xanderfrangos** [comment]
Thanks for the localization! A nearly-complete translation is preferable to none at all. 

I noticed that GENERIC_NO_DISPLAYS_SHORT, PANEL_BUTTON_LINK_LEVELS, and SETTINGS_GENERAL_THEME_TITLE are in full English. Is that intentional? I just want to double check before I merge.

**Comment by CodeF0x** [comment]
Oh, you're right! Seems like I forgot to translate them. I'll add another commit.

**Comment by CodeF0x** [comment]
@xanderfrangos Hi, I've added the missing translations. Now everything should be fine. Thanks for the  proofreading, I would have totally missed it.

**Comment by xanderfrangos** [comment]
@CodeF0x No worries. Thanks again for the localization! I should have an update out with this in a few days.

**Pull request merged**
